"use strict";
var STATE_DIR = "/sdcard/Download/Operit/finger_tips";
var STATE_FILE = STATE_DIR + "/state.json";
var CONFIG = { pingThrottleMs: 4000, pauseGapMs: 15000, minNoteMs: 20000, orphanAfterMs: 600000, minAbandonedMs: 5000, maxPingsPerSegment: 300, maxInputSegments: 100, maxAbandonedDrafts: 10 };
var queue = Promise.resolve(), inputGate = {}, pendingNotes = {};
function str(v) { return v === null || v === undefined ? "" : String(v); }
function num(v, fallback) { var n = Number(v); return isFinite(n) ? n : Number(fallback || 0); }
function emptyState() { return { schemaVersion: 1, chats: {} }; }
function emptyChat() { return { draftSession: null, abandonedDrafts: [], pendingNote: null, lastSubmittedAt: 0 }; }
function draft(now) { var t = num(now, Date.now()); return { startedAt: t, updatedAt: t, inputSegments: [] }; }
function segment(now) { var t = num(now, Date.now()); return { startedAt: t, lastInputAt: t, closedAt: 0, closeReason: "", active: true, pings: [t] }; }
function normalizeSegment(raw) { var s = raw && typeof raw === "object" ? raw : {}, p = Array.isArray(s.pings) ? s.pings.filter(function(x) { return typeof x === "number" && isFinite(x) && x >= 0; }).slice(-CONFIG.maxPingsPerSegment) : []; var start = num(s.startedAt, p.length ? p[0] : 0); return { startedAt: start, lastInputAt: num(s.lastInputAt, p.length ? p[p.length - 1] : start), closedAt: num(s.closedAt, 0), closeReason: str(s.closeReason), active: !!s.active, pings: p }; }
function normalizeDraft(raw) { if (!raw || typeof raw !== "object") return null; return { startedAt: num(raw.startedAt, 0), updatedAt: num(raw.updatedAt, 0), inputSegments: Array.isArray(raw.inputSegments) ? raw.inputSegments.map(normalizeSegment).slice(-CONFIG.maxInputSegments) : [] }; }
function normalizeAbandoned(raw) { var s = raw && typeof raw === "object" ? raw : {}; return { startedAt: num(s.startedAt, 0), endedAt: num(s.endedAt, 0), durationMs: Math.max(0, num(s.durationMs, 0)), reason: str(s.reason || "timeout"), createdAt: num(s.createdAt, s.endedAt || 0) }; }
function normalizeChat(raw) { var s = raw && typeof raw === "object" ? raw : {}; return { draftSession: normalizeDraft(s.draftSession), abandonedDrafts: Array.isArray(s.abandonedDrafts) ? s.abandonedDrafts.map(normalizeAbandoned).slice(-CONFIG.maxAbandonedDrafts) : [], pendingNote: s.pendingNote && typeof s.pendingNote === "object" ? { createdAt: num(s.pendingNote.createdAt, 0), injectedAt: num(s.pendingNote.injectedAt, 0) } : null, lastSubmittedAt: num(s.lastSubmittedAt, 0) }; }
function normalizeState(raw) { if (!raw || typeof raw !== "object" || Number(raw.schemaVersion) !== 1) return emptyState(); var out = emptyState(); var chats = raw.chats && typeof raw.chats === "object" ? raw.chats : {}; Object.keys(chats).forEach(function(id) { out.chats[id] = normalizeChat(chats[id]); }); return out; }
async function readState() { try { var r = await Tools.Files.read({ path: STATE_FILE, environment: "android" }); return normalizeState(JSON.parse(str(r && r.content))); } catch (_) { return emptyState(); } }
async function writeState(s) { await Tools.Files.mkdir(STATE_DIR, true, "android"); await Tools.Files.write(STATE_FILE, JSON.stringify(normalizeState(s)), false, "android"); }
function enqueue(fn) { var run = queue.then(fn, fn); queue = run.then(function() {}, function() {}); return run; }
function getChat(state, id) { id = str(id).trim(); if (!id) return null; state.chats[id] = normalizeChat(state.chats[id]); return state.chats[id]; }
function activeSegment(d) { if (!d || !d.inputSegments.length) return null; var s = d.inputSegments[d.inputSegments.length - 1]; return s.active ? s : null; }
function closeSegment(d, reason, now) { var s = activeSegment(d); if (!s) return null; s.closedAt = num(s.lastInputAt, now); s.closeReason = str(reason); s.active = false; return s; }
function recordPing(d, now) { var t = num(now, Date.now()), s = activeSegment(d) || (d.inputSegments.push(segment(t)), d.inputSegments[d.inputSegments.length - 1]); var last = s.pings.length ? s.pings[s.pings.length - 1] : 0; if (!last || t - last >= CONFIG.pingThrottleMs) s.pings = s.pings.concat([t]).slice(-CONFIG.maxPingsPerSegment); s.lastInputAt = t; d.updatedAt = t; return s; }
function duration(d) { return d && Array.isArray(d.inputSegments) ? d.inputSegments.reduce(function(total, s) { return total + Math.max(0, num(s.lastInputAt, s.startedAt) - num(s.startedAt, 0)); }, 0) : 0; }
function pauses(d, gap) { var count = 0, limit = num(gap, CONFIG.pauseGapMs); (d && d.inputSegments || []).forEach(function(s) { for (var i = 1; i < s.pings.length; i++) if (s.pings[i] - s.pings[i - 1] > limit) count++; }); return count; }
function minuteText(ms) { var total = Math.max(0, Math.floor(num(ms, 0) / 1000)); if (total < 60) return "约" + total + "秒"; var m = Math.floor(total / 60), s = total % 60; return s ? "约" + m + "分" + s + "秒" : "约" + m + "分钟"; }
function rhythmText(d, opts) { if (!d) return ""; opts = opts || {}; var ms = duration(d), p = pauses(d, num(opts.pauseGapSec, 15) * 1000); if (ms < num(opts.minNoteSec, 10) * 1000 && !p) return ""; var text = "这条消息" + (str(opts.userName).trim() || "TA") + "输入了" + minuteText(ms); return p ? text + "，中途停下来想了" + p + "次。" : text + "。"; }
function abandoned(d, reason, now) { if (!d) return null; closeSegment(d, reason, now); var ms = duration(d); if (ms < CONFIG.minAbandonedMs) return null; return { startedAt: d.startedAt, endedAt: d.updatedAt, durationMs: ms, reason: str(reason || "timeout"), createdAt: num(now, Date.now()) }; }
function gc(chat, now, orphanMinutes) { if (!chat || !chat.draftSession) return null; if (num(now, Date.now()) - chat.draftSession.updatedAt > num(orphanMinutes, 10) * 60000) { var a = abandoned(chat.draftSession, "timeout", now); if (a) chat.abandonedDrafts = chat.abandonedDrafts.concat([a]).slice(-CONFIG.maxAbandonedDrafts); chat.draftSession = null; return a; } return null; }
function abandonedText(a, now, userName) { if (!a) return ""; var ago = Math.max(0, Math.floor((num(now, Date.now()) - a.endedAt) / 60000)); return (str(userName).trim() || "TA") + " " + ago + "分钟前打过" + minuteText(a.durationMs) + "的字，那条没有发出来。"; }
function buildNote(chat, now, opts) { opts = opts || {}; gc(chat, now, opts.orphanMinutes); var list = []; var last = chat.abandonedDrafts.length ? chat.abandonedDrafts[chat.abandonedDrafts.length - 1] : null; if (opts.injectRhythm !== false && last) list.push(abandonedText(last, now, opts.userName)); var r = opts.injectRhythm === false ? "" : rhythmText(chat.draftSession, opts); if (r) list.push(r); return list.join("\n"); }
async function handleInputChanged(chatId, hasText, now) { var id = str(chatId).trim(); if (!id) return { ok: false }; var t = num(now, Date.now()); var gate = inputGate[id] || { at: 0, text: false }; if (hasText && gate.text && t - gate.at < CONFIG.pingThrottleMs) return { ok: true, throttled: true }; inputGate[id] = { at: t, text: !!hasText }; return enqueue(async function() { var state = await readState(), chat = getChat(state, id); gc(chat, t, 10); if (hasText) { if (!chat.draftSession) chat.draftSession = draft(t); recordPing(chat.draftSession, t); } else if (chat.draftSession) { var a = abandoned(chat.draftSession, "cleared", t); if (a) chat.abandonedDrafts = chat.abandonedDrafts.concat([a]).slice(-CONFIG.maxAbandonedDrafts); chat.draftSession = null; } await writeState(state); return { ok: true }; }); }
async function handleSubmitRequested(chatId, now, allow, opts) { return enqueue(async function() { var state = await readState(), chat = getChat(state, chatId); if (!chat) return { ok: false, note: "" }; var note = allow === false ? "" : buildNote(chat, num(now, Date.now()), opts || {}); if (note) { pendingNotes[str(chatId).trim()] = note; chat.pendingNote = { createdAt: num(now, Date.now()), injectedAt: 0 }; } else { delete pendingNotes[str(chatId).trim()]; chat.pendingNote = null; } chat.draftSession = null; chat.abandonedDrafts = []; await writeState(state); return { ok: true, note: note }; }); }
async function takePendingNote(chatId, now) { return enqueue(async function() { var id = str(chatId).trim(), state = await readState(), chat = getChat(state, id), note = pendingNotes[id] || ""; if (!chat || !chat.pendingNote || !note) return { ok: true, note: "" }; chat.pendingNote.injectedAt = num(now, Date.now()); await writeState(state); return { ok: true, note: note }; }); }
async function clearInjectedPending(chatId) { return enqueue(async function() { var id = str(chatId).trim(), state = await readState(), chat = getChat(state, id); if (!chat) return { ok: false }; if (chat.pendingNote && chat.pendingNote.injectedAt) { chat.pendingNote = null; delete pendingNotes[id]; } await writeState(state); return { ok: true }; }); }
async function peek(chatId) { return enqueue(async function() { var state = await readState(), id = str(chatId).trim(); if (id) { var chat = getChat(state, id); return { state: chat, config: CONFIG }; } var ids = Object.keys(state.chats); return { chatIds: ids, chatCount: ids.length, config: CONFIG }; }); }
async function clear(chatId) { return enqueue(async function() { var state = await readState(), id = str(chatId).trim(); if (id) delete state.chats[id]; else state = emptyState(); delete pendingNotes[id]; delete inputGate[id]; await writeState(state); return { ok: true, clearedChatId: id || null }; }); }
exports.STATE_FILE = STATE_FILE; exports.CONFIG = CONFIG; exports.handleInputChanged = handleInputChanged; exports.handleSubmitRequested = handleSubmitRequested; exports.takePendingNote = takePendingNote; exports.clearInjectedPending = clearInjectedPending; exports.peek = peek; exports.clear = clear;
exports._test = { emptyState: emptyState, emptyChat: emptyChat, draft: draft, recordPing: recordPing, duration: duration, pauses: pauses, rhythmText: rhythmText, abandoned: abandoned, normalizeState: normalizeState, minuteText: minuteText };
