"use strict";
var PREFS_NAME = "toolpkg_finger_tips";
var SETTINGS_KEY = "finger_tips_settings";
var DEFAULT_SETTINGS = { enabled: true, scope: "global", boundChatId: "", boundChatTitle: "", userName: "TA", injectRhythm: true, minNoteSec: 10, pauseGapSec: 15, orphanMinutes: 10 };
function str(v) { return v === null || v === undefined ? "" : String(v); }
function int(v, fallback, min, max) { var n = Number(v); if (!isFinite(n)) n = fallback; n = Math.round(n); return Math.max(min, Math.min(max, n)); }
function sanitize(input) { var s = input && typeof input === "object" ? input : {}; return { enabled: s.enabled === undefined ? true : !!s.enabled, scope: s.scope === "bound" ? "bound" : "global", boundChatId: str(s.boundChatId).trim(), boundChatTitle: str(s.boundChatTitle).trim(), userName: str(s.userName).trim() || "TA", injectRhythm: true, minNoteSec: int(s.minNoteSec, 10, 5, 120), pauseGapSec: int(s.pauseGapSec, 15, 5, 120), orphanMinutes: int(s.orphanMinutes, 10, 2, 60) }; }
function prefs() { if (typeof Java === "undefined" || typeof Java.getApplicationContext !== "function") throw new Error("application_context_unavailable"); return Java.getApplicationContext().getSharedPreferences(PREFS_NAME, 0); }
function loadSettings() { try { var raw = str(prefs().getString(SETTINGS_KEY, "")).trim(); return sanitize(raw ? JSON.parse(raw) : DEFAULT_SETTINGS); } catch (_) { return sanitize(DEFAULT_SETTINGS); } }
function saveSettings(patch) { var next = sanitize(Object.assign({}, loadSettings(), patch || {})); prefs().edit().putString(SETTINGS_KEY, JSON.stringify(next)).apply(); return next; }
function shouldInject(chatId, value) { var s = value || loadSettings(); return !!s.enabled && (s.scope === "global" || (!!s.boundChatId && str(chatId).trim() === s.boundChatId)); }
async function chats() { return await Tools.Chat.listChats({ limit: 200 }) || { chats: [], currentChatId: "" }; }
async function bindCurrentChat() { var r = await chats(), id = str(r.currentChatId || (typeof getChatId === "function" ? getChatId() : "")).trim(), list = Array.isArray(r.chats) ? r.chats : [], c = list.filter(function(x) { return str(x.id).trim() === id; })[0]; if (!c || !id) return { success: false, message: "当前对话不可用", settings: loadSettings() }; return { success: true, settings: saveSettings({ scope: "bound", boundChatId: id, boundChatTitle: str(c.title).trim() }), chat: c }; }
async function bindChatByExactTitle(title) { var q = str(title).trim(); if (!q) return { success: false, message: "请输入完整对话标题", settings: loadSettings() }; var r = await chats(), list = Array.isArray(r.chats) ? r.chats : [], hits = list.filter(function(x) { return str(x.title).trim() === q; }); if (!hits.length) return { success: false, message: "未找到标题严格一致的对话", settings: loadSettings() }; if (hits.length > 1) return { success: false, message: "存在多个同名对话，请改用绑定当前对话", settings: loadSettings() }; return { success: true, settings: saveSettings({ scope: "bound", boundChatId: str(hits[0].id).trim(), boundChatTitle: q }), chat: hits[0] }; }
function statusDescription(chatId) { var s = loadSettings(), injection = !s.enabled ? "已禁用" : (s.scope === "global" ? "已启用 · 所有对话" : (shouldInject(chatId, s) ? "已启用 · 仅绑定对话" : "已启用 · 当前对话不在绑定范围")); return "注入状态：" + injection + "\n显示门槛：" + s.minNoteSec + "秒\n停顿门槛：" + s.pauseGapSec + "秒\n未发送判定：" + s.orphanMinutes + "分钟"; }
exports.DEFAULT_SETTINGS = DEFAULT_SETTINGS; exports.sanitizeSettings = sanitize; exports.loadSettings = loadSettings; exports.saveSettings = saveSettings; exports.shouldInject = shouldInject; exports.bindCurrentChat = bindCurrentChat; exports.bindChatByExactTitle = bindChatByExactTitle; exports.statusDescription = statusDescription;