"use strict";
var settings = require("../core/settings.js");
function state(ctx, key, initial) { var p = ctx.useState(key, initial); return { value: p[0], set: p[1] }; }
function toast(v) { try { if (typeof Tools !== "undefined" && Tools.System && typeof Tools.System.toast === "function") Tools.System.toast(String(v || "")); } catch (_) {} }
function section(ctx, icon, title) { return ctx.UI.Row({ fillMaxWidth: true, verticalAlignment: "center" }, [ctx.UI.Icon({ name: icon, tint: "primary", size: 20 }), ctx.UI.Spacer({ width: 8 }), ctx.UI.Text({ text: title, style: "titleMedium", fontWeight: "bold", color: "primary" })]); }
function toggle(ctx, title, subtitle, checked, onChange) { return ctx.UI.Surface({ fillMaxWidth: true, shape: { cornerRadius: 10 }, containerColor: "surfaceVariant" }, [ctx.UI.Row({ fillMaxWidth: true, padding: 12, verticalAlignment: "center", horizontalArrangement: "spaceBetween" }, [ctx.UI.Column({ weight: 1, spacing: 3 }, [ctx.UI.Text({ text: title, style: "bodyMedium", fontWeight: "bold" }), ctx.UI.Text({ text: subtitle, style: "bodySmall", color: "onSurfaceVariant" })]), ctx.UI.Switch({ checked: checked, onCheckedChange: onChange })])]); }
function button(ctx, text, selected, onClick, enabled) { return ctx.UI.Button({ text: text, weight: 1, minWidth: 0, enabled: enabled !== false, onClick: onClick, containerColor: selected ? "primary" : "surfaceVariant", contentColor: selected ? "onPrimary" : "onSurfaceVariant" }); }
function step(ctx, text, onClick) { return ctx.UI.Button({ text: text, width: 36, height: 36, minWidth: 0, contentPadding: 0, onClick: onClick, textAlign: "center" }); }
function stepper(ctx, title, subtitle, value, unit, min, max, delta, onChange) { return ctx.UI.Surface({ fillMaxWidth: true, shape: { cornerRadius: 10 }, containerColor: "surfaceVariant" }, [ctx.UI.Column({ fillMaxWidth: true, padding: 12, spacing: 8 }, [ctx.UI.Text({ text: title, style: "bodyMedium", fontWeight: "bold" }), ctx.UI.Text({ text: subtitle, style: "bodySmall", color: "onSurfaceVariant" }), ctx.UI.Row({ fillMaxWidth: true, spacing: 8, verticalAlignment: "center" }, [step(ctx, "-", function() { onChange(Math.max(min, value - delta)); }), ctx.UI.Row({ weight: 1, horizontalArrangement: "center" }, [ctx.UI.Text({ text: String(value) + unit, style: "titleMedium", fontWeight: "bold" })]), step(ctx, "+", function() { onChange(Math.min(max, value + delta)); })])])]); }
function statusText(v) { if (!v.enabled) return "注入状态：已禁用\n提示：修改配置后，输入栏快捷菜单状态显示可能延迟。"; var scope = v.scope === "global" ? "所有对话" : "仅「" + (v.boundChatTitle || v.boundChatId || "未绑定") + "」对话"; return "注入状态：已启用\n注入范围：" + scope + "\nFingertips生成判定 " + v.minNoteSec + " 秒 | 输入停顿判定 " + v.pauseGapSec + " 秒 | 欲言又止判定 " + v.orphanMinutes + " 分钟\n提示：修改配置后，输入栏快捷菜单状态显示可能延迟。"; }
function preview(v) { var n = v.userName || "TA", lines = ["[Fingertips 指尖语气]", "以下是" + n + "输入这条消息时留下的节奏，仅供感受。", "这条消息" + n + "输入了约X分X秒，中途停下来想了X次。", "欲言又止：", n + " X分钟前输入了约X分X秒，那条没有发出来。"]; return lines.join("\n"); }
function Screen(ctx) {
  var initial = settings.loadSettings();
  var enabled = state(ctx, "enabled", initial.enabled), scope = state(ctx, "scope", initial.scope), title = state(ctx, "title", initial.boundChatTitle || ""), chatId = state(ctx, "chatId", initial.boundChatId || ""), userName = state(ctx, "userName", initial.userName || "TA"), min = state(ctx, "min", initial.minNoteSec), pause = state(ctx, "pause", initial.pauseGapSec), orphan = state(ctx, "orphan", initial.orphanMinutes), notice = state(ctx, "notice", ""), error = state(ctx, "error", "");
  function current() { return { enabled: enabled.value, scope: scope.value, boundChatTitle: title.value, boundChatId: chatId.value, userName: userName.value, injectRhythm: true, minNoteSec: min.value, pauseGapSec: pause.value, orphanMinutes: orphan.value }; }
  function sync(v) { enabled.set(v.enabled); scope.set(v.scope); title.set(v.boundChatTitle || ""); chatId.set(v.boundChatId || ""); userName.set(v.userName || "TA"); min.set(v.minNoteSec); pause.set(v.pauseGapSec); orphan.set(v.orphanMinutes); }
  function save(patch, message) { try { var v = settings.saveSettings(patch); sync(v); notice.set(message || "已保存"); error.set(""); toast(message || "已保存"); } catch (e) { error.set("保存失败：" + String((e && e.message) || e)); notice.set(""); } }
  async function bindCurrent() { try { var r = await settings.bindCurrentChat(); if (!r.success) throw new Error(r.message); sync(r.settings); notice.set("已绑定当前对话"); } catch (e) { error.set(String((e && e.message) || e)); } }
  async function bindTitle() { try { var r = await settings.bindChatByExactTitle(title.value); if (!r.success) throw new Error(r.message); sync(r.settings); notice.set("已精确绑定：" + r.settings.boundChatTitle); } catch (e) { error.set(String((e && e.message) || e)); } }
  var v = current(), children = [ctx.UI.Row({ fillMaxWidth: true, verticalAlignment: "center" }, [ctx.UI.Icon({ name: "touchApp", tint: "primary", size: 24 }), ctx.UI.Spacer({ width: 8 }), ctx.UI.Text({ text: "指尖语气 Fingertips", style: "headlineSmall", fontWeight: "bold" })]), ctx.UI.Text({ text: "让 AI 感知你的输入时长和欲言又止，随用户消息注入Fingertips 显性附件。运行时会临时读取输入事件，用于判断输入状态和附加节奏摘要；不会保存、上传或注入输入原文，只记录输入时间、停顿和持续时长等节奏数据。", style: "bodySmall", color: "onSurfaceVariant" }), ctx.UI.Surface({ fillMaxWidth: true, shape: { cornerRadius: 10 }, containerColor: "surfaceVariant" }, [ctx.UI.Column({ fillMaxWidth: true, padding: 12, spacing: 3 }, [section(ctx, "tune", "当前配置"), ctx.UI.Text({ text: statusText(v), style: "bodySmall", color: "onSurfaceVariant" })])]), toggle(ctx, "启用 Fingertips 注入", "注入消息的输入时长和停顿次数。和输入栏快捷菜单里的指尖语气开关同步。", enabled.value, function(x) { save({ enabled: x }, x ? "已开启 Fingertips 注入" : "已关闭 Fingertips 注入"); }), section(ctx, "link", "注入范围"), ctx.UI.Row({ fillMaxWidth: true, spacing: 8 }, [button(ctx, "所有对话", scope.value === "global", function() { save({ scope: "global" }, "已设为所有对话"); }), button(ctx, "仅绑定对话", scope.value === "bound", function() { save({ scope: "bound" }, "已设为仅绑定对话"); })]), ctx.UI.TextField({ label: "绑定对话标题（精确匹配）", value: title.value, enabled: scope.value === "bound", onValueChange: title.set, singleLine: true }), ctx.UI.Row({ fillMaxWidth: true, spacing: 8 }, [ctx.UI.Button({ text: "绑定标题", weight: 1, enabled: scope.value === "bound", onClick: bindTitle }), ctx.UI.Button({ text: "绑定当前对话", weight: 1, enabled: scope.value === "bound", onClick: bindCurrent })]), ctx.UI.Text({ text: "绑定 ID：" + (chatId.value || "未绑定"), style: "bodySmall", color: "onSurfaceVariant" }), section(ctx, "person", "User 显示名"), ctx.UI.TextField({ label: "用于 Fingertips 注入", value: userName.value, onValueChange: userName.set, singleLine: true }), ctx.UI.Button({ text: "保存显示名", fillMaxWidth: true, onClick: function() { save({ userName: userName.value }, "已保存显示名"); } }), section(ctx, "schedule", "输入节奏设置"), stepper(ctx, "Fingertips生成判定时间", "总输入时长超过此时间才生成Fingertips附件；仅记录输入时间和持续时长，不保存输入原文。", min.value, " 秒", 5, 120, 5, function(x) { save({ minNoteSec: x }, "Fingertips生成判定时间已设为" + x + "秒"); }), stepper(ctx, "输入停顿判定时间", "输入间隔超过此时间记为一次停顿；仅记录停顿时间，不保存输入原文。", pause.value, " 秒", 5, 120, 5, function(x) { save({ pauseGapSec: x }, "输入停顿判定时间已设为" + x + "秒"); }), stepper(ctx, "欲言又止判定时间", "超过此时间没有继续输入或发送时，记为一段搁置的欲言又止；不保存输入原文。", orphan.value, " 分钟", 2, 60, 1, function(x) { save({ orphanMinutes: x }, "欲言又止判定时间已设为" + x + "分钟"); }), section(ctx, "visibility", "注入预览示例"), ctx.UI.Surface({ fillMaxWidth: true, shape: { cornerRadius: 10 }, containerColor: "surfaceVariant" }, [ctx.UI.Text({ text: preview(v), style: "bodySmall", color: "onSurfaceVariant", padding: 12 })])];
  if (notice.value) children.push(ctx.UI.Text({ text: notice.value, color: "primary", style: "bodySmall" })); if (error.value) children.push(ctx.UI.Text({ text: error.value, color: "error", style: "bodySmall" })); return ctx.UI.LazyColumn({ fillMaxSize: true, padding: 16, spacing: 12 }, children);
}
exports.Screen = Screen;